Initializing repo_version to false breaks validation later in init.pp:282:
    if $repo_version == undef {

Generates an incorrect error message:

Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: false is not a string.  It looks to be a FalseClass at
/etc/puppet/modules/elasticsearch/manifests/init.pp:285 on node xxx